var links = new Array(  "https://www.firstnational.com/site/personal/index.fhtml",
						"https://www.firstnational.com/site/small-business/index.fhtml",
						"https://www.firstnational.com/site/corporate/index.fhtml",
						"https://www.firstnational.com/site/about-us/",
						"https://firstnational.locatorsearch.com/",
						"https://www.firstnational.com/RetailWeb/default/contactus/SHOW_FORM/form",
						"https://www.firstnational.com/site/security-center/",
						"https://www.firstnational.com/site/personal/banking/",
						"https://www.firstnational.com/site/personal/banking/checking-accounts/",
						"https://www.firstnational.com/site/personal/banking/checking-accounts/first-at-work-checking.fhtml",
						"https://www.firstnational.com/site/personal/banking/savings-accounts/",
						"https://www.firstnational.com/site/personal/banking/savings-accounts/savings-accounts.fhtml",
						"https://www.firstnational.com/site/personal/banking/savings-accounts/money-market.fhtml",
						"https://www.firstnational.com/site/personal/banking/savings-accounts/minor-savings-accounts.fhtml",
						"https://www.firstnational.com/site/personal/banking/savings-accounts/health-savings-account.fhtml",
						"https://www.firstnational.com/site/personal/banking/cd-ira-accounts/",
						"https://www.firstnational.com/site/personal/banking/cd-ira-accounts/cd-accounts.fhtml",
						"https://www.firstnational.com/site/personal/banking/cd-ira-accounts/ira-accounts.fhtml",
						"https://www.firstnational.com/site/personal/banking/cd-ira-accounts/roth-ira-accounts.fhtml",
						"https://www.firstnational.com/site/personal/banking/cd-ira-accounts/educational-savings-accounts.fhtml",
						"https://www.firstnational.com/site/personal/banking/online-services/",
						"https://www.firstnational.com/site/personal/banking/online-services/online-banking.fhtml",
						"https://www.firstnational.com/site/personal/banking/online-services/billpay.fhtml",
						"https://www.firstnational.com/site/personal/banking/online-services/statements.fhtml",
						"https://www.firstnational.com/site/personal/banking/online-services/alerts.fhtml",
						"https://www.firstnational.com/site/personal/banking/online-services/credit-card-payments.fhtml",
						"https://www.firstnational.com/site/personal/banking/online-services/activate-card.fhtml",
						"https://www.firstnational.com/site/personal/banking/online-services/my-deals.fhtml",
						"https://www.firstnational.com/site/personal/banking/mobile-banking.fhtml",
						"https://www.firstnational.com/site/personal/banking/foreign-currency.fhtml",
						"https://www.firstnational.com/site/personal/banking/personal-rates.fhtml",
						"https://www.firstnational.com/site/personal/lending/",
						"https://www.firstnational.com/site/personal/lending/mortgage-loans.fhtml",
						"https://www.firstnational.com/site/personal/lending/home-equity-loans.fhtml",
						"https://www.firstnational.com/site/personal/lending/auto-loans.fhtml",
						"https://www.firstnational.com/site/personal/lending/personal-loans-lines-of-credit.fhtml",
						"https://www.firstnational.com/site/personal/lending/rates.fhtml",
						"https://www.firstnational.com/site/personal/credit-card/",
						"https://www.firstnational.com/site/personal/credit-card/amex/",
						"https://www.firstnational.com/site/personal/credit-card/amex/amex-graphite.fhtml",
						"https://www.firstnational.com/site/personal/credit-card/amex/amex-standard.fhtml",
						"https://www.firstnational.com/site/personal/credit-card/discover/",
						"https://www.firstnational.com/site/personal/credit-card/discover/discover-card.fhtml",
						"https://www.firstnational.com/site/personal/credit-card/mastercard/",
						"https://www.firstnational.com/site/personal/credit-card/mastercard/mc-platinum.fhtml",
						"https://www.firstnational.com/site/personal/credit-card/visa/",
						"https://www.firstnational.com/site/personal/credit-card/visa/visa-maxrewards.fhtml",
						"https://www.firstnational.com/site/personal/credit-card/visa/visa-platinum.fhtml",
						"https://www.firstnational.com/site/personal/credit-card/visa/visa-secured.fhtml",
						"https://www.firstnational.com/site/personal/credit-card/online-services/index.fhtml",
						"https://www.firstnational.com/site/personal/credit-card/online-services/online-banking.fhtml",
						"https://www.firstnational.com/site/personal/credit-card/online-services/statements.fhtml",
						"https://www.firstnational.com/site/personal/credit-card/online-services/alerts.fhtml",
						"https://www.firstnational.com/site/personal/credit-card/online-services/credit-card-payments.fhtml",
						"https://www.firstnational.com/site/personal/credit-card/online-services/activate-card.fhtml",
						"https://www.firstnational.com/site/personal/credit-card/online-services/my-deals.fhtml",
						"https://www.firstnational.com/site/personal/credit-card/benefits/",
						"https://www.firstnational.com/site/personal/credit-card/benefits/firstguard.fhtml",
						"https://www.firstnational.com/site/personal/credit-card/benefits/design-your-card.fhtml",
						"https://www.firstnational.com/RetailWeb/default/cardservices/application-status/show-form",
						"https://www.firstnational.com/site/personal/wealth-investing/",
						"https://www.firstnational.com/site/personal/wealth-investing/investments-planning.fhtml",
						"https://www.firstnational.com/site/personal/wealth-investing/wealth-solutions.fhtml",
						"https://www.firstnational.com/site/personal/wealth-investing/tributary-funds.fhtml",
						"https://www.firstnational.com/site/personal/wealth-investing/529-savings-plans.fhtml",
						"https://clientpoint.fisglobal.com/tdcb/main/UserLogon?bankNumber=ng&subProduct=fnbtrust",
						"https://www.firstnational.com/site/personal/resource-center/",
						"https://www.firstnational.com/site/personal/resource-center/smart-credit-management/index.fhtml",
						"https://www.firstnational.com/site/personal/resource-center/bank-green/index.fhtml",
						"https://www.firstnational.com/site/personal/resource-center/newsletters/index.fhtml",
						"https://www.firstnational.com/site/personal/resource-center/newsletters/first-focus/index.fhtml",
						"https://www.firstnational.com/site/personal/resource-center/newsletters/estate-planning-updates.fhtml",
						"https://www.firstnational.com/site/security-center/index.fhtml",
						"https://www.firstnational.com/site/personal/banking/index",
						"https://www.firstnational.com/site/personal/banking/checking-accounts/index.fhtml",
						"https://www.firstnational.com/site/personal/banking/checking-accounts/first-at-work-checking.fhtml",
						"https://www.firstnational.com/site/personal/banking/savings-accounts/",
						"https://www.firstnational.com/site/personal/banking/savings-accounts/savings-accounts.fhtml",
						"https://www.firstnational.com/site/personal/banking/savings-accounts/money-market.fhtml",
						"https://www.firstnational.com/site/personal/banking/savings-accounts/minor-savings-accounts.fhtml",
						"https://www.firstnational.com/site/personal/banking/savings-accounts/health-savings-account.fhtml",
						"https://www.firstnational.com/site/personal/banking/cd-ira-accounts/",
						"https://www.firstnational.com/site/personal/banking/cd-ira-accounts/cd-accounts.fhtml",
						"https://www.firstnational.com/site/personal/banking/cd-ira-accounts/ira-accounts.fhtml",
						"https://www.firstnational.com/site/personal/banking/cd-ira-accounts/roth-ira-accounts.fhtml",
						"https://www.firstnational.com/site/personal/banking/cd-ira-accounts/educational-savings-accounts.fhtml",
						"https://www.firstnational.com/site/personal/banking/online-services/",
						"https://www.firstnational.com/site/personal/banking/online-services/online-banking.fhtml",
						"https://www.firstnational.com/site/personal/banking/online-services/billpay.fhtml",
						"https://www.firstnational.com/site/personal/banking/online-services/statements.fhtml",
						"https://www.firstnational.com/site/personal/banking/online-services/alerts.fhtml",
						"https://www.firstnational.com/site/personal/banking/online-services/credit-card-payments.fhtml",
						"https://www.firstnational.com/site/personal/banking/online-services/activate-card.fhtml",
						"https://www.firstnational.com/site/personal/banking/online-services/my-deals.fhtml",
						"https://www.firstnational.com/site/personal/banking/mobile-banking.fhtml",
						"https://www.firstnational.com/site/personal/banking/currency.fhtml",
						"https://www.firstnational.com/site/personal/banking/personal-rates.fhtml",
						"https://www.firstnational.com/site/personal/lending/",
						"https://www.firstnational.com/site/personal/lending/mortgage-loans.fhtml",
						"https://www.firstnational.com/site/personal/lending/home-equity-loans.fhtml",
						"https://www.firstnational.com/site/personal/lending/auto-loans.fhtml",
						"https://www.firstnational.com/site/personal/lending/personal-loans-lines-of-credit.fhtml",
						"https://www.firstnational.com/site/personal/lending/rates.fhtml",
						"https://www.firstnational.com/site/personal/credit-card/",
						"https://www.firstnational.com/site/personal/credit-card/amex/",
						"https://www.firstnational.com/site/personal/credit-card/amex/amex-graphite.fhtml",
						"https://www.firstnational.com/site/personal/credit-card/amex/amex-standard.fhtml",
						"https://www.firstnational.com/site/personal/credit-card/discover/",
						"https://www.firstnational.com/site/personal/credit-card/discover/discover-card.fhtml",
						"https://www.firstnational.com/site/personal/credit-card/mastercard/",
						"https://www.firstnational.com/site/personal/credit-card/mastercard/mc-platinum.fhtml",
						"https://www.firstnational.com/site/personal/credit-card/visa/",
						"https://www.firstnational.com/site/personal/credit-card/visa/visa-maxrewards.fhtml",
						"https://www.firstnational.com/site/personal/credit-card/visa/visa-platinum.fhtml",
						"https://www.firstnational.com/site/personal/credit-card/visa/visa-secured.fhtml",
						"https://www.firstnational.com/site/personal/credit-card/online-services/index.fhtml",
						"https://www.firstnational.com/site/personal/credit-card/online-services/online-banking.fhtml",
						"https://www.firstnational.com/site/personal/credit-card/online-services/statements.fhtml",
						"https://www.firstnational.com/site/personal/credit-card/online-services/alerts.fhtml",
						"https://www.firstnational.com/site/personal/credit-card/online-services/credit-card-payments.fhtml",
						"https://www.firstnational.com/site/personal/credit-card/online-services/activate-card.fhtml",
						"https://www.firstnational.com/site/personal/credit-card/online-services/my-deals.fhtml",
						"https://www.firstnational.com/site/personal/credit-card/benefits/",
						"https://www.firstnational.com/site/personal/credit-card/benefits/firstguard.fhtml",
						"https://www.firstnational.com/site/personal/credit-card/benefits/design-your-card.fhtml",
						"https://www.firstnational.com/RetailWeb/kansas/cardservices/application-status/show-form",
						"https://www.firstnational.com/site/personal/wealth-investing/",
						"https://www.firstnational.com/site/personal/wealth-investing/investments-planning.fhtml",
						"https://www.firstnational.com/site/personal/wealth-investing/wealth-solutions.fhtml",
						"https://www.firstnational.com/site/personal/wealth-investing/tributary-funds.fhtml",
						"https://www.firstnational.com/site/personal/wealth-investing/529-savings-plans.fhtml",
						"https://www.firstnational.com/site/personal/resource-center/",
						"https://www.firstnational.com/site/personal/resource-center/smart-credit-management/index.fhtml",
						"https://www.firstnational.com/site/personal/resource-center/bank-green/index.fhtml",
						"https://www.firstnational.com/site/personal/resource-center/newsletters/index.fhtml",
						"https://www.firstnational.com/site/personal/resource-center/newsletters/first-focus/index.fhtml",
						"https://www.firstnational.com/site/personal/resource-center/newsletters/estate-planning-updates.fhtml",
						"https://www.firstnational.com/site/small-business/banking/",
						"https://www.firstnational.com/site/small-business/banking/checking-accounts/",
						"https://www.firstnational.com/site/small-business/banking/checking-accounts/free-checking.fhtml",
						"https://www.firstnational.com/site/small-business/banking/checking-accounts/300class-checking.fhtml",
						"https://www.firstnational.com/site/small-business/banking/checking-accounts/not-for-profit-checking.fhtml",
						"https://www.firstnational.com/site/small-business/banking/savings-accounts/",
						"https://www.firstnational.com/site/small-business/banking/savings-accounts/first-savings.fhtml",
						"https://www.firstnational.com/site/small-business/banking/savings-accounts/money-market.fhtml",
						"https://www.firstnational.com/site/small-business/banking/savings-accounts/first-health-savings-account.fhtml",
						"https://www.firstnational.com/site/small-business/banking/cds.fhtml",
						"https://www.firstnational.com/site/small-business/banking/credit-cards/",
						"https://www.firstnational.com/site/small-business/banking/credit-cards/visa/",
						"https://www.firstnational.com/site/small-business/banking/credit-cards/online-services/",
						"https://www.firstnational.com/site/small-business/banking/credit-cards/online-services/account-alerts.fhtml",
						"https://www.firstnational.com/site/small-business/banking/credit-cards/online-services/business-forms.fhtml",
						"https://www.firstnational.com/site/small-business/banking/credit-cards/online-services/management-reports.fhtml",
						"https://www.firstnational.com/site/small-business/banking/credit-cards/online-services/online-access.fhtml",
						"https://www.firstnational.com/site/small-business/banking/credit-cards/benefits/benefits.fhtml",
						"https://www.firstnational.com/site/small-business/banking/global-banking.fhtml",
						"https://www.firstnational.com/site/small-business/banking/community-banking.fhtml",
						"https://www.firstnational.com/site/small-business/banking/online-banking.fhtml",
						"https://www.firstnational.com/site/small-business/lending/",
						"https://www.firstnational.com/site/small-business/lending/loans/",
						"https://www.firstnational.com/site/small-business/lending/loans/small-business-loans.fhtml",
						"https://www.firstnational.com/site/small-business/lending/loans/sba-loans.fhtml",
						"https://www.firstnational.com/site/small-business/lending/loans/lines-of-credit.fhtml",
						"https://www.firstnational.com/site/small-business/lending/credit-cards/",
						"https://www.firstnational.com/site/small-business/lending/credit-cards/visa/",
						"https://www.firstnational.com/site/small-business/lending/credit-cards/online-services/",
						"https://www.firstnational.com/site/small-business/lending/credit-cards/online-services/account-alerts.fhtml",
						"https://www.firstnational.com/site/small-business/lending/credit-cards/online-services/business-forms.fhtml",
						"https://www.firstnational.com/site/small-business/lending/credit-cards/online-services/management-reports.fhtml",
						"https://www.firstnational.com/site/small-business/lending/credit-cards/online-services/online-access.fhtml",
						"https://www.firstnational.com/site/small-business/lending/credit-cards/benefits/benefits.fhtml",
						"https://www.firstnational.com/RetailWeb/default/cardservices/application-status/show-form",
						"https://www.firstnational.com/site/small-business/wealth-investing/",
						"https://www.firstnational.comsite/small-business/wealth-investing/capital-markets.fhtml",
						"https://www.firstnational.com/site/small-business/wealth-investing/investments-planning.fhtml",
						"https://www.firstnational.com/site/small-business/wealth-investing/wealth-solutions.fhtml",
						"https://www.firstnational.com/site/small-business/wealth-investing/tributary-funds.fhtml",
						"https://www.firstnational.com/site/small-business/wealth-investing/529-savings-plans.fhtml",
						"https://www.firstnational.com/site/small-business/business-services/",
						"https://www.firstnational.com/site/small-business/business-services/credit-card-processing.fhtml",
						"https://www.firstnational.com/site/small-business/business-services/first-at-work.fhtml",
						"https://www.firstnational.com/site/small-business/business-services/fnts.fhtml",
						"https://www.firstnational.com/site/small-business/business-services/online-banking.fhtml",
						"https://www.firstnational.com/site/small-business/resource-center",
						"https://www.firstnational.com/site/small-business/resource-center/business-bankers.fhtml",
						"https://www.firstnational.com/site/small-business/resource-center/business-spotlight.fhtml",
						"https://www.firstnational.com/site/small-business/resource-center/newsletters/index.fhtml",
						"https://www.firstnational.com/site/small-business/resource-center/newsletters/first-focus/index.fhtml",
						"https://www.firstnational.com/site/small-business/resource-center/newsletters/capital-markets.fhtml",
						"https://www.firstnational.com/site/corporate/banking/",
						"https://www.firstnational.com/site/corporate/banking/deposits.fhtml",
						"https://www.firstnational.com/site/corporate/banking/treasury-management.fhtml",
						"https://www.firstnational.com/site/corporate/banking/global-banking.fhtml",
						"https://www.firstnational.com/site/corporate/banking/credit-cards/",
						"https://www.firstnational.com/site/corporate/banking/credit-cards/visa/",
						"https://www.firstnational.com/site/corporate/banking/credit-cards/mastercard/",
						"https://www.firstnational.com/site/corporate/banking/credit-cards/online-services/",
						"https://www.firstnational.com/site/corporate/banking/credit-cards/online-services/account-alerts.fhtml",
						"https://www.firstnational.com/site/corporate/banking/credit-cards/online-services/business-forms.fhtml",
						"https://www.firstnational.com/site/corporate/banking/banking/credit-cards/online-services/management-reports.fhtml",
						"https://www.firstnational.com/site/corporate/banking/credit-cards/online-services/online-access.fhtml",
						"https://www.firstnational.com/site/corporate/banking/credit-cards/benefits/benefits.fhtml",
						"https://www.firstnational.com/site/corporate/banking/online-banking/",
						"https://www.firstnational.com/site/corporate/loans-financing/",
						"https://www.firstnational.com/site/corporate/loans-financing/agribusiness.fhtml",
						"https://www.firstnational.com/site/corporate/loans-financing/agribusiness/first-ag-rewards.fhtml",
						"https://www.firstnational.com/site/corporate/loans-financing/corporate-lending.fhtml",
						"https://www.firstnational.com/site/corporate/loans-financing/commercial-real-estate.fhtml",
						"https://www.firstnational.com/site/corporate/loans-financing/credit-cards/",
						"https://www.firstnational.com/site/corporate/loans-financing/credit-cards/visa/",
						"https://www.firstnational.com/site/corporate/loans-financing/credit-cards/mastercard/",
						"https://www.firstnational.com/site/corporate/loans-financing/credit-cards/online-services/",
						"https://www.firstnational.com/site/corporate/loans-financing/credit-cards/online-services/account-alerts.fhtml",
						"https://www.firstnational.com/site/corporate/loans-financing/credit-cards/online-services/business-forms.fhtml",
						"https://www.firstnational.com/site/corporate/loans-financing/banking/credit-cards/online-services/management-reports.fhtml",
						"https://www.firstnational.com/site/corporate/loans-financing/credit-cards/online-services/online-access.fhtml",
						"https://www.firstnational.com/site/corporate/loans-financing/credit-cards/benefits/benefits.fhtml",
						"https://www.firstnational.com/site/corporate/investing/",
						"https://www.firstnational.com/site/corporate/investing/capital-markets.fhtml",
						"https://www.firstnational.com/site/corporate/investing/wealth-solutions.fhtml",
						"https://www.firstnational.com/site/corporate/investing/tributary-capital-mgmt.fhtml",
						"https://www.firstnational.com/site/small-business/wealth-investing/529-savings-plans.fhtml",
						"https://www.firstnational.com/site/corporate/specialized-services/",
						"https://www.firstnational.com/site/corporate/specialized-services/renewable-fuels.fhtml",
						"https://www.firstnational.com/site/corporate/specialized-services/fnts.fhtml",
						"https://www.firstnational.com/site/corporate/specialized-services/financial-institutions/",
						"https://www.firstnational.com/site/corporate/specialized-services/financial-institutions/capital-markets.fhtml",
						"https://www.firstnational.com/site/corporate/specialized-services/financial-institutions/correspondent-banking.fhtml",
						"https://www.firstnational.com/site/corporate/specialized-services/financial-institutions/treasury-management.fhtml",
						"https://www.firstnational.com/site/corporate/specialized-services/financial-institutions/credit-card.fhtml",
						"https://www.firstnational.com/site/corporate/specialized-services/employee-banking.fhtml",
						"https://www.firstnational.com/site/corporate/specialized-services/credit-card-processing.fhtml",
						"https://www.firstnational.com/site/corporate/specialized-services/healthcare-banking.fhtml",
						"https://www.firstnational.com/site/about-us/",
						"https://www.firstnational.com/site/about-us/company/",
						"https://www.firstnational.com/site/about-us/leadership-team/",
						"https://www.firstnational.com/site/about-us/newsroom/index.fhtml",
						"https://www.firstnational.com/site/about-us/newsroom/latest-news.fhtml",
						"https://www.firstnational.com/site/about-us/newsroom/awards-ranking.fhtml",
						"https://www.firstnational.com/site/about-us/newsroom/advertising.fhtml",
						"https://www.firstnational.com/site/about-us/in-the-community/",
						"https://www.firstnational.com/site/about-us/in-the-community/community-events.fhtml",
						"https://www.firstnational.com/site/about-us/in-the-community/community-album.fhtml",
						"https://www.firstnational.com/site/about-us/in-the-community/sculpture-parks.fhtml",
						"https://www.firstnational.com/site/about-us/careers/",
						"https://www.firstnational.com/site/about-us/careers/employee-benefits.fhtml",
						"https://www.firstnational.com/site/about-us/careers/emerging-professionals.fhtml",
						"https://www.firstnational.com/site/about-us/careers/reasons-to-live-in-omaha.fhtml",
						"https://www.firstnational.com/site/about-us/careers/contact-us.fhtml",
						"https://www.firstnational.com/site/about-us/careers/e-verify.fhtml",
						"https://www.firstnational.com/site/about-us/careers/job-applicant-privacy-policy.fhtml",
						"https://www.firstnational.com/site/about-us/careers/",
						"https://www.firstnational.com/comp/popups/privacy-policy.fhtml",
						"https://www.firstnational.com/comp/popups/security-statement.fhtml",
						"https://www.firstnational.com/site/sitemap/");

var titles = new Array("Personal",
					"Small Business",
					"Corporate",
					"About Us",
					"ATM/Branch Locator",
					"Contact Us",
					"Information Security Center",
					"Banking",
					"First National Checking",
					"First At Work",
					"Savings Accounts",
					"Savings",
					"Money Market",
					"Minor Savings",
					"National Health Savings",
					"IRAs",
					"CDs",
					"Traditional IRA",
					"Roth IRA",
					"Educational Savings Account",
					"Online Services",
					"Online Banking",
					"BillPay",
					"Paperless Statements",
					"Account Alerts",
					"Credit Card Payments",
					"Activate Credit Card",
					"My Deals",
					"Mobile Banking",
					"Foreign Currency",
					"Rates",
					"Lending",
					"Mortgage",
					"Home Equity",
					"Auto",
					"Personal",
					"Rates",
					"Credit Cards",
					"American Express",
					"First National Bank Graphite American Express Card",
					"First National Bank American Express Card",
					"Discover",
					"First National Bank Discover Card",
					"MasterCard",
					"Platinum Edition MasterCard Card",
					"Visa",
					"Maximum Rewards Visa Card",
					"Platinum Edition Visa Card",
					"Secured Visa Card",
					"Online Services",
					"Online Banking",
					"Paperless Statements",
					"Account Alerts",
					"Credit Card Payments",
					"Activate Credit Card",
					"My Deals",
					"Benefits",
					"FirstGuard",
					"Design Your Card",
					"View Credit Card Application Status",
					"Wealth Investing",
					"Investments Planning",
					"Wealth Management",
					"Tributary  Funds",
					"529 Savings Plans(NEST)",
					"Client Point",
					"Resource Center",
					"Smart Credit Management",
					"Bank Green",
					"Newsletters",
					"First Focus",
					"Estate Planning Updates",
					"Information Security Center",
					"Banking",
					"First National Checking",
					"First At Work",
					"Savings Accounts",
					"Savings",
					"Money Market",
					"Minor Savings",
					"First National Health Savings",
					"CD's ; IRA's",
					"CDs",
					"Traditional IRA",
					"Roth IRA",
					"Educational Savings Account",
					"Online Services",
					"Online Banking",
					"BillPay",
					"Paperless Statements",
					"Account Alerts",
					"Credit Card Payments",
					"Activate Credit Card",
					"My Deals",
					"Mobile Banking",
					"Foreign Currency",
					"Rates",
					"Lending",
					"Mortgage",
					"Home Equity",
					"Auto",
					"Personal",
					"Rates",
					"Credit Cards",
					"American Express",
					"First National Bank Graphite American Express Card",
					"First National Bank American Express Card",
					"Discover",
					"First National Bank Discover Card",
					"MasterCard",
					"Platinum Edition MasterCard Card",
					"Visa",
					"Maximum Rewards Visa Card",
					"Platinum Edition Visa Card",
					"Secured Visa Card",
					"Online Services",
					"Online Banking",
					"Paperless Statements",
					"Account Alerts",
					"Credit Card Payments",
					"Activate Credit Card",
					"My Deals",
					"Benefits",
					"FirstGuard",
					"Design Your Card",
					"View Credit Card Application Status",
					"Wealth ; Investing",
					"Investments ; Planning",
					"Wealth Management",
					"Tributary Funds",
					"529 Savings Plans (NEST)",
					"Resource Center",
					"Smart Credit Management",
					"Bank Green",
					"Newsletters",
					"First Focus",
					"Estate Planning Updates",
					"Banking",
					"Checking Accounts",
					"Free Checking",
					"300 Class Checking",
					"Not For Profit Checking",
					"Savings Accounts",
					"Savings",
					"Money Market",
					"Health Savings",
					"CD's",
					"Credit Cards",
					"Visa",
					"Online Services",
					"Account Alerts",
					"Business Forms",
					"Management Reports",
					"Online Access",
					"Benefits",
					"Global Banking",
					"Community Banking",
					"Online Banking",
					"Lending",
					"Loans",
					"Small Business",
					"SBA Loans",
					"Lines of Credit",
					"Credit Cards",
					"Visa",
					"Online Services",
					"Account Alerts",
					"Business Forms",
					"Management Reports",
					"Online Access",
					"Benefits",
					"View Credit Card Application Status",
					"Wealth ; Investing",
					"Capital Markets",
					"Investments ; Planning",
					"Wealth Management",
					"Tributary Funds",
					"529 Savings Plans (NEST)",
					"Business Services",
					"Credit Card Processing",
					"Employee Banking - First at Work",
					"First National Technology Services",
					"Online Banking",
					"Resource Center",
					"Business Bankers",
					"Business Spotlight",
					"Newsletters",
					"First Focus",
					"Capital Markets Newsletter",
					"Banking",
					"Deposits",
					"Corporate Treasury Services",
					"Global Banking",
					"Credit Cards",
					"Visa",
					"MasterCard",
					"Online Services",
					"Account Alerts",
					"Business Forms",
					"Management Reports",
					"Online Access",
					"Benefits",
					"Online Banking",
					"Loans ; Financing",
					"AgriBusiness",
					"First AgRewards",
					"Corporate Lending",
					"Commercial Real Estate",
					"Credit Cards",
					"Visa",
					"MasterCard",
					"Online Services",
					"Account Alerts",
					"Business Forms",
					"Management Reports",
					"Online Access",
					"Benefits",
					"Investing",
					"Capital Markets",
					"Wealth Management",
					"Tributary Capital Management",
					"529 Savings Plans (NEST)",
					"Specialized Services",
					"Renewable Fuels",
					"Technology Solutions",
					"Solutions for Financial Institutions",
					"Capital Markets",
					"Correspondent Banking",
					"Corporate Treasury Services",
					"Credit Card Solutions",
					"Employee Banking - First at Work",
					"Credit Card Processing",
					"Healthcare Banking",
					"About Us",
					"Company",
					"Leadership Team",
					"Newsroom",
					"Latest News",
					"Awards 7 Rankings",
					"Advertising",
					"First in the Community",
					"Community Events",
					"Community Album",
					"Sculpture Park",
					"Careers",
					"Employee Benefits",
					"Emerging Professionals",
					"Reasons to live in Omaha",
					"Contact Us",
					"E-Verify",
					"Job Applicant Privacy Policy",
					"Careers",
					"Privacy Policy",
					"Security Statement",
					"Site Map"
					);
